import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import docmarketIcon from "../../assets/docmarket-icon.png";

function Icon({name,size=19}){const c={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:2,strokeLinecap:"round",strokeLinejoin:"round","aria-hidden":true};const p={heart:<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/>,bag:<><path d="M6 8h12l1 13H5L6 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></>,user:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,store:<><path d="M3 10h18"/><path d="M5 10v10h14V10"/><path d="m4 4-1 6h18l-1-6H4Z"/></>,home:<><path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/></>,docs:<><path d="M6 3h9l4 4v14H6z"/><path d="M15 3v5h5M9 12h7M9 16h7"/></>,users:<><path d="M8 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM16 12a3 3 0 1 0 0-6"/><path d="M2 21c0-4 2-6 6-6s6 2 6 6"/></>,services:<><path d="M12 3 9.5 8.5 4 11l5.5 2.5L12 19l2.5-5.5L20 11l-5.5-2.5L12 3Z"/><path d="M5 4v4M3 6h4M19 17v4M17 19h4"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>,help:<><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.7 2.2c-.9.5-1.4 1.1-1.4 2.3M12 17h.01"/></>,close:<path d="M6 6l12 12M18 6 6 18"/>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>};return <svg {...c}>{p[name]||p.menu}</svg>}

export function DocMarketBrand(){return <Link className="docmarket-brand" to="/" aria-label="ДокМаркет — на главную"><img className="docmarket-brand-icon" src={docmarketIcon} alt=""/><span className="docmarket-brand-copy"><strong><span>Док</span><em>Маркет</em></strong><small>Маркетплейс документов</small></span></Link>}

export function DocMarketBottomNav(){const{pathname}=useLocation(),{user}=useAuth();const items=[["/","home","Главная",pathname==="/"],["/market","store","Каталог",pathname==="/market"],["/MyDocuments","docs","Документы",pathname.startsWith("/MyDocuments")],["/market/favorites","heart","Избранное",pathname.startsWith("/market/favorites")],[user?"/Dashboard":"/Login","user","Профиль",pathname.startsWith("/Dashboard")||pathname.startsWith("/Profile")||pathname.startsWith("/Login")]];return <nav className="dm-global-bottom" aria-label="Основная навигация">{items.map(([to,icon,label,active])=><Link className={active?"active":""} to={to} key={label}><Icon name={icon} size={20}/><span>{label}</span></Link>)}</nav>}

export default function DocMarketHeader(){const{user}=useAuth();const[menuOpen,setMenuOpen]=useState(false),close=()=>setMenuOpen(false);return <><style>{`.dm-global-bottom{display:none}@media(max-width:760px){body{padding-bottom:calc(76px + env(safe-area-inset-bottom))}.dm-global-bottom{position:fixed;z-index:1000;left:8px;right:8px;bottom:max(7px,env(safe-area-inset-bottom));height:58px;padding:5px 4px;display:grid;grid-template-columns:repeat(5,1fr);background:rgba(7,17,29,.97);border:1px solid #3f3428;border-radius:17px;box-shadow:0 12px 35px #0009;backdrop-filter:blur(14px)}.dm-global-bottom a{display:grid;place-items:center;align-content:center;gap:2px;color:#8995a5;text-decoration:none;font-size:.56rem;font-weight:800;min-width:0}.dm-global-bottom a.active{color:#d99a4b}.dm-global-bottom svg{width:20px;height:20px}.dm-mobile-bottom{display:none!important}.docmarket-mobile-menu a{color:#e9edf2}.docmarket-mobile-menu a svg{color:#d99a4b}}`}</style><header className="docmarket-header"><div className="docmarket-header-inner"><DocMarketBrand/><nav className="docmarket-main-nav"><Link to="/market">Каталог</Link><Link to="/#verified-sellers">Селлеры</Link><Link to="/partners">Партнёры</Link><Link to="/reviews">Отзывы</Link><Link to="/seller">Стать селлером</Link></nav><nav className="docmarket-actions"><Link to="/market/favorites" aria-label="Избранное"><Icon name="heart"/><span>Избранное</span></Link><Link to="/market/cart" aria-label="Корзина"><Icon name="bag"/><span>Корзина</span></Link><Link to={user?"/Dashboard":"/Login"} aria-label={user?"Кабинет":"Войти"}><Icon name="user"/><span>{user?"Кабинет":"Войти"}</span></Link><button className="docmarket-menu-button" type="button" aria-label={menuOpen?"Закрыть меню":"Открыть меню"} onClick={()=>setMenuOpen(v=>!v)}><Icon name={menuOpen?"close":"menu"}/></button></nav></div>{menuOpen&&<div className="docmarket-mobile-menu"><Link to="/market" onClick={close}><Icon name="store"/>Каталог документов</Link><Link to="/market/favorites" onClick={close}><Icon name="heart"/>Избранное</Link><Link to="/market/cart" onClick={close}><Icon name="bag"/>Корзина</Link><Link to={user?"/Dashboard":"/Login"} onClick={close}><Icon name="user"/>{user?"Личный кабинет":"Войти"}</Link><Link to="/seller" onClick={close}><Icon name="store"/>Стать селлером</Link><Link to="/partners" onClick={close}><Icon name="users"/>Партнёры</Link><Link to="/#services" onClick={close}><Icon name="services"/>Сервисы</Link><Link to="/dosudebka" onClick={close}><Icon name="docs"/>Досудебка</Link><Link to="/about" onClick={close}><Icon name="info"/>О ДокМаркете</Link><Link to="/support" onClick={close}><Icon name="help"/>Помощь и поддержка</Link></div>}</header><DocMarketBottomNav/></>}
