import { useState } from "react";
import { Link, useLocation } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import docmarketIcon from "../../assets/docmarket-icon.png";

function Icon({name,size=19}){const c={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round",strokeLinejoin:"round","aria-hidden":true};const p={heart:<><path d="M20.4 5.3c-2-2-5.2-2-7.2 0L12 6.5l-1.2-1.2c-2-2-5.2-2-7.2 0s-2 5.2 0 7.2L12 21l8.4-8.5c2-2 2-5.2 0-7.2Z"/><path className="dm-icon-glow" d="M6.6 7.2c.8-.8 2-.9 2.9-.3"/></>,bag:<><path d="M5.5 8.5h13l1.2 12h-15l.8-12Z"/><path d="M9 9V7a3 3 0 0 1 6 0v2"/><path className="dm-icon-glow" d="M8 13h8"/></>,user:<><circle cx="12" cy="8" r="3.6"/><path d="M5.2 20.5v-1.2a6.8 6.8 0 0 1 13.6 0v1.2"/><circle className="dm-icon-glow" cx="18.3" cy="5.2" r="2"/><path className="dm-icon-check" d="m17.4 5.2.6.6 1.1-1.2"/></>,store:<><rect x="4" y="4" width="6.2" height="6.2" rx="1.4"/><rect x="13.8" y="4" width="6.2" height="6.2" rx="1.4"/><rect x="4" y="13.8" width="6.2" height="6.2" rx="1.4"/><rect x="13.8" y="13.8" width="6.2" height="6.2" rx="1.4"/><path className="dm-icon-glow" d="M15.8 6.1H18v2.1"/></>,home:<><path d="m3.5 11 8.5-7.5 8.5 7.5"/><path d="M5.5 10v10.5h13V10M9.2 20.5v-6.3h5.6v6.3"/><path className="dm-icon-glow" d="M8 10.5h8"/></>,docs:<><path d="M7.5 3.5h8l3 3v14h-11z"/><path d="M15.5 3.5v4h4M10.5 11.5h5M10.5 15h5"/><path className="dm-icon-glow" d="M4.5 7v14h10"/></>,users:<><circle cx="8.5" cy="9" r="3.5"/><circle cx="16.5" cy="10" r="3"/><path d="M2.5 21c.5-5 2.5-7.5 6-7.5s5.5 2.5 6 7.5M14 14.5c4 0 6.5 2.2 7 6.5"/></>,services:<><path d="M12 3 9.5 8.5 4 11l5.5 2.5L12 19l2.5-5.5L20 11l-5.5-2.5L12 3Z"/><path d="M5 4v4M3 6h4M19 17v4M17 19h4"/></>,info:<><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>,help:<><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.5 2.5 0 1 1 3.7 2.2c-.9.5-1.4 1.1-1.4 2.3M12 17h.01"/></>,close:<path d="M6 6l12 12M18 6 6 18"/>,menu:<path d="M4 7h16M4 12h16M4 17h16"/>};return <svg {...c}>{p[name]||p.menu}</svg>}

export function DocMarketBrand(){return <Link className="docmarket-brand" to="/" aria-label="ДокМаркет — на главную"><img className="docmarket-brand-icon" src={docmarketIcon} alt=""/><span className="docmarket-brand-copy"><strong><span>Док</span><em>Маркет</em></strong><small>Маркетплейс документов</small></span></Link>}

export function DocMarketBottomNav(){const{pathname}=useLocation(),{user}=useAuth();const items=[["/","home","Главная",pathname==="/"],["/market","store","Каталог",pathname==="/market"],["/MyDocuments","docs","Документы",pathname.startsWith("/MyDocuments")],["/market/favorites","heart","Избранное",pathname.startsWith("/market/favorites")],[user?"/Dashboard":"/Login","user","Профиль",pathname.startsWith("/Dashboard")||pathname.startsWith("/Profile")||pathname.startsWith("/Login")]];return <nav className="dm-global-bottom" aria-label="Основная навигация">{items.map(([to,icon,label,active])=><Link className={active?"active":""} to={to} key={label}><Icon name={icon} size={20}/><span>{label}</span></Link>)}</nav>}

export default function DocMarketHeader(){const{user}=useAuth();const[menuOpen,setMenuOpen]=useState(false),close=()=>setMenuOpen(false);return <><style>{`.dm-global-bottom{display:none}@media(max-width:760px){body{padding-bottom:calc(76px + env(safe-area-inset-bottom))}.dm-global-bottom{position:fixed;z-index:1000;left:8px;right:8px;bottom:max(7px,env(safe-area-inset-bottom));height:58px;padding:5px 4px;display:grid;grid-template-columns:repeat(5,1fr);background:rgba(7,17,29,.97);border:1px solid #3f3428;border-radius:17px;box-shadow:0 12px 35px #0009;backdrop-filter:blur(14px)}.dm-global-bottom a{display:grid;place-items:center;align-content:center;gap:2px;color:#8995a5;text-decoration:none;font-size:.56rem;font-weight:800;min-width:0}.dm-global-bottom a.active{color:#d99a4b}.dm-global-bottom svg{width:20px;height:20px}.dm-mobile-bottom{display:none!important}.docmarket-mobile-menu a{color:#e9edf2}.docmarket-mobile-menu a svg{color:#d99a4b}}`}</style><header className="docmarket-header"><div className="docmarket-header-inner"><DocMarketBrand/><nav className="docmarket-main-nav"><Link to="/market">Каталог</Link><Link to="/#verified-sellers">Селлеры</Link><Link to="/partners">Партнёры</Link><Link to="/reviews">Отзывы</Link><Link to="/seller">Стать селлером</Link></nav><nav className="docmarket-actions"><Link to="/market/favorites" aria-label="Избранное"><Icon name="heart"/><span>Избранное</span></Link><Link to="/market/cart" aria-label="Корзина"><Icon name="bag"/><span>Корзина</span></Link><Link to={user?"/Dashboard":"/Login"} aria-label={user?"Кабинет":"Войти"}><Icon name="user"/><span>{user?"Кабинет":"Войти"}</span></Link><button className="docmarket-menu-button" type="button" aria-label={menuOpen?"Закрыть меню":"Открыть меню"} onClick={()=>setMenuOpen(v=>!v)}><Icon name={menuOpen?"close":"menu"}/></button></nav></div>{menuOpen&&<div className="docmarket-mobile-menu"><Link to="/market" onClick={close}><Icon name="store"/>Каталог документов</Link><Link to="/market/favorites" onClick={close}><Icon name="heart"/>Избранное</Link><Link to="/market/cart" onClick={close}><Icon name="bag"/>Корзина</Link><Link to={user?"/Dashboard":"/Login"} onClick={close}><Icon name="user"/>{user?"Личный кабинет":"Войти"}</Link><Link to="/seller" onClick={close}><Icon name="store"/>Стать селлером</Link><Link to="/partners" onClick={close}><Icon name="users"/>Партнёры</Link><Link to="/#services" onClick={close}><Icon name="services"/>Сервисы</Link><Link to="/dosudebka" onClick={close}><Icon name="docs"/>Досудебка</Link><Link to="/about" onClick={close}><Icon name="info"/>О ДокМаркете</Link><Link to="/support" onClick={close}><Icon name="help"/>Помощь и поддержка</Link></div>}</header><DocMarketBottomNav/></>}
