import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { listPublicSellers } from "@/marketplace/services/sellerProfileService";
import { loadPublishedCatalog } from "@/marketplace/services/catalogService";

const initialsOf = name => String(name || "Селлер").split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join("").toUpperCase();

export default function PublicSellerShowcase(){
 const [sellers,setSellers]=useState([]); const [catalog,setCatalog]=useState([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;Promise.all([listPublicSellers(8),loadPublishedCatalog()]).then(([sellerRows,itemRows])=>{if(!active)return;setSellers(sellerRows||[]);setCatalog(itemRows||[])}).catch(()=>{if(active){setSellers([]);setCatalog([])}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[]);
 const cards=useMemo(()=>sellers.map(seller=>{const items=catalog.filter(item=>item.providerId===seller.user_id);return {...seller,documents:items.filter(item=>item.type!=="service").length,services:items.filter(item=>item.type==="service").length}}),[sellers,catalog]);
 if(loading)return null;
 return <section id="specialists" className="real-sellers"><style>{css}</style><div className="real-sellers-head"><div><span className="market-kicker">СЕЛЛЕРЫ ДОКМАРКЕТА</span><h2 className="market-heading">Селлеры с проверенными витринами</h2><p className="market-lead">После проверки в витрине будут доступны документы, услуги, рейтинг и отзывы по завершённым заказам.</p></div>{cards.length>0&&<Link className="market-action" to="/RegisterLawyer">Стать селлером</Link>}</div>{cards.length?<div className="real-sellers-grid">{cards.map(seller=><Link className="real-seller-card" to={`/market/specialist/${seller.user_id}`} key={seller.user_id}><div className="real-seller-top"><span className="real-seller-avatar">{initialsOf(seller.display_name)}</span><div><span className="market-badge">✓ Проверен</span><h3>{seller.display_name}</h3><p>{seller.headline||"Селлер ДокМаркета"}</p></div></div><div className="real-seller-stats"><span><b>{Number(seller.rating||0)>0?`★ ${Number(seller.rating).toFixed(1)}`:"Новый"}</b><small>{Number(seller.reviews_count||0)>0?`${Number(seller.reviews_count)} отзывов`:"Нет отзывов"}</small></span><span><b>{seller.documents}</b><small>документов</small></span><span><b>{seller.services}</b><small>услуг</small></span><span><b>{Number(seller.completed_orders||0)}</b><small>заказов</small></span></div><div className="real-seller-tags">{(seller.specializations||[]).slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div><strong className="real-seller-link">Открыть витрину →</strong></Link>)}</div>:<div className="real-sellers-empty"><h3>Витрины появятся после проверки</h3><p>Перед публикацией мы проверяем данные селлера, документы и услуги. После одобрения витрина появится здесь автоматически.</p><Link className="market-primary" to="/RegisterLawyer">Подать заявку</Link></div>}</section>
}
const css=`.real-sellers{box-sizing:border-box;width:min(100% - 28px,1180px);margin:20px auto 28px;padding:26px;border-radius:24px;background:linear-gradient(145deg,rgba(17,37,58,.94),rgba(10,20,35,.94));border:1px solid rgba(218,181,111,.2)}.real-sellers-head{display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:18px}.real-sellers-head .market-lead{max-width:850px;margin-bottom:0}.real-sellers-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.real-seller-card{padding:18px;border-radius:18px;text-decoration:none;color:inherit;background:rgba(7,17,29,.5);border:1px solid rgba(255,255,255,.08);transition:.2s}.real-seller-card:hover{transform:translateY(-2px);border-color:rgba(241,213,138,.32)}.real-seller-top{display:flex;gap:12px;align-items:center}.real-seller-avatar{width:50px;height:50px;flex:0 0 50px;display:grid;place-items:center;border-radius:14px;color:#102235;background:linear-gradient(135deg,#f1d58a,#d8b463);font-weight:900}.real-seller-top h3{color:#fff;margin:5px 0 3px;font-size:1rem}.real-seller-top p{color:#94a3b8;margin:0;font-size:.73rem}.real-seller-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin:14px 0}.real-seller-stats span{padding:9px;border-radius:10px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06)}.real-seller-stats b,.real-seller-stats small{display:block}.real-seller-stats b{color:#fff;font-size:.78rem}.real-seller-stats small{color:#64748b;font-size:.6rem;margin-top:2px}.real-seller-tags{display:flex;gap:6px;flex-wrap:wrap}.real-seller-tags span{padding:5px 7px;border-radius:999px;color:#cbd5e1;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.07);font-size:.62rem}.real-seller-link{display:block;margin-top:14px;color:#f1d58a;font-size:.73rem}.real-sellers-empty{text-align:center;padding:30px 16px;border-radius:16px;background:rgba(7,17,29,.42);border:1px dashed rgba(241,213,138,.2)}.real-sellers-empty h3{color:#fff;margin:0 0 7px}.real-sellers-empty p{color:#94a3b8;max-width:650px;margin:0 auto 16px;line-height:1.55;font-size:.8rem}@media(max-width:700px){.real-sellers{width:calc(100% - 20px);margin:14px auto 18px;padding:14px;border-radius:18px}.real-sellers-head{align-items:flex-start;flex-direction:column;gap:10px;margin-bottom:12px}.real-sellers-grid{grid-template-columns:1fr}.real-seller-stats{grid-template-columns:1fr 1fr}.real-sellers-head>.market-action{width:100%}.real-sellers-empty{padding:18px 10px}.real-sellers-empty h3{font-size:1rem}.real-sellers-empty p{font-size:.72rem;margin-bottom:12px}}`;
