import { useCallback, useEffect, useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import { claimParticipantSlot,getCompletedParticipants,getRoom,getTotalParticipants,saveOwnerParticipant,saveParticipant,updateRoom } from "@/services/collectiveService";
import StepIndicator from "@/components/generator/StepIndicator";
import Step1Category from "@/components/generator/Step1Category";
import Step2Mode from "@/components/generator/Step2Mode";
import Step3Respondent from "@/components/generator/Step3Respondent";
import Step4Claimants from "@/components/generator/Step4Claimants";
import Step5Circumstances from "@/components/generator/Step5Circumstances";
import Step6Evidence from "@/components/generator/Step6Evidence";
import Step7Generate from "@/components/generator/Step7Generate";
import CollectiveProgress from "@/components/generator/CollectiveProgress";
const LS_KEY="legalpro_generator_v2",LEGACY_DRAFT_KEYS=["dosudebka_generator_draft","dosudebka_generator_v2"],ACTIVE_OWNER_ROOM_KEY="legalpro_collective_active_owner_room";
const joinParticipantKey=r=>`dosudebka_join_participant_${r}`,joinDraftKey=(r,p)=>`dosudebka_join_draft_${r}_${p}`,ownerDraftKey=r=>`dosudebka_owner_draft_${r}`;
const initialClaimData=()=>({type:"",mode:"individual",workers:[{id:0}],employer:{},circumstances:{},evidence:[],witness:null,collectiveFinalized:false});
function normalizeClaimData(raw={}){const type=raw.type||raw.category||"",employer=raw.employer||raw.respondent||{},workers=raw.workers?.length?raw.workers:raw.claimant?[{...raw.claimant,id:raw.claimant.id??0}]:[{id:0}];return{...initialClaimData(),...raw,type,category:type,employer,respondent:employer,workers,claimant:workers[0]||{},circumstances:raw.circumstances||{},evidence:Array.isArray(raw.evidence)?raw.evidence:[]}}
function readSoloDraft(){try{for(const key of[LS_KEY,...LEGACY_DRAFT_KEYS]){const saved=localStorage.getItem(key);if(!saved)continue;const parsed=JSON.parse(saved);if(!parsed?.claimData||parsed.claimData.mode==="collective"||parsed.claimData.isJoiner)continue;return{claimData:normalizeClaimData(parsed.claimData),currentStep:Math.min(7,Math.max(1,Number(parsed.currentStep)||1)),sourceKey:key}}}catch{console.error("Не удалось прочитать локальный черновик генератора.")}return null}
function memberToWorker(member,index=0){return{...(member?.claimantData||{}),id:index,name:member?.claimantData?.name||member?.name||"",address:member?.claimantData?.address||member?.address||"",phone:member?.claimantData?.phone||member?.phone||"",email:member?.claimantData?.email||member?.email||""}}
export default function Generator(){const location=useLocation(),initialDraftRef=useRef(null);if(initialDraftRef.current===null)initialDraftRef.current=readSoloDraft()||false;const[currentStep,setCurrentStep]=useState(()=>initialDraftRef.current?.currentStep||1),[claimData,setClaimData]=useState(()=>initialDraftRef.current?.claimData||initialClaimData()),[showCollectiveProgress,setShowCollectiveProgress]=useState(false),[isJoiner,setIsJoiner]=useState(false),[joinRoom,setJoinRoom]=useState(null),[joinLoading,setJoinLoading]=useState(false),[error,setError]=useState("");const totalSteps=7;
useEffect(()=>{const params=new URLSearchParams(location.search),roomId=params.get("room");if(roomId)initJoiner(roomId)},[location.search]);
async function initJoiner(roomId){setJoinLoading(true);try{const tokenKey=joinParticipantKey(roomId),existingToken=localStorage.getItem(tokenKey)||localStorage.getItem(`legalpro_collective_participant_${roomId}`),result=await claimParticipantSlot(roomId,existingToken||undefined),room=result?.room,member=result?.participant;if(!room||!member){setError("Комната совместной претензии не найдена.");return}const participantToken=member.participantToken||member.participantId;localStorage.setItem(tokenKey,participantToken);localStorage.removeItem(`legalpro_collective_participant_${roomId}`);setJoinRoom(room);setIsJoiner(true);const newData={...initialClaimData(),mode:"collective",isJoiner:true,roomId,collectiveParticipantId:participantToken,maxMembers:getTotalParticipants(room),totalParticipants:getTotalParticipants(room),employer:room.employer||{},type:room.type||"",subtype:room.subtype||"",workers:[memberToWorker(member)],circumstances:member.circumstancesData||{},evidence:member.evidenceData?.selected||[],evidenceFiles:member.evidenceData?.files||{},selectedLegalOptions:member.selectedLegalOptions||[]},savedDraft=member.status==="completed"?null:localStorage.getItem(joinDraftKey(roomId,participantToken)),parsedDraft=savedDraft?JSON.parse(savedDraft):null,restoredData=parsedDraft?.claimData?{...newData,...parsedDraft.claimData,roomId,collectiveParticipantId:participantToken,isJoiner:true}:newData;setClaimData(restoredData);setCurrentStep(member.status==="completed"?7:Math.max(3,Number(parsedDraft?.currentStep||3)));setShowCollectiveProgress(member.status==="completed");setError("")}catch(e){setError(e?.message==="ROOM_FULL"?"Все места в совместной претензии уже заполнены.":"Не удалось открыть совместную комнату. Попробуйте ещё раз.")}finally{setJoinLoading(false)}}
useEffect(()=>{if(!claimData.type)return;try{const storageKey=claimData.isJoiner&&claimData.roomId&&claimData.collectiveParticipantId?joinDraftKey(claimData.roomId,claimData.collectiveParticipantId):claimData.mode==="collective"&&claimData.roomId?ownerDraftKey(claimData.roomId):LS_KEY;localStorage.setItem(storageKey,JSON.stringify({claimData,currentStep}))}catch{setError("Не удалось сохранить локальную резервную копию черновика.")}},[claimData,currentStep]);
const nextStep=()=>setCurrentStep(s=>Math.min(s+1,totalSteps)),prevStep=()=>setCurrentStep(s=>Math.max(s-1,1)),updateClaimData=useCallback(updates=>setClaimData(prev=>{const next={...prev,...updates};if("type" in updates||"category" in updates){next.type=updates.type||updates.category||prev.type||prev.category||"";next.category=next.type}if("employer" in updates||"respondent" in updates){next.employer=updates.employer||updates.respondent||{};next.respondent=next.employer}if("workers" in updates||"claimant" in updates){next.workers=updates.workers||(updates.claimant?[{...updates.claimant,id:updates.claimant.id??0}]:prev.workers);next.claimant=next.workers?.[0]||{}}return next}),[]);
const reset=()=>{setClaimData(initialClaimData());setCurrentStep(1);setShowCollectiveProgress(false);setIsJoiner(false);setJoinRoom(null);localStorage.removeItem(LS_KEY);if(!isJoiner){localStorage.removeItem(ACTIVE_OWNER_ROOM_KEY);localStorage.removeItem("legalpro_room_owner")}},clearCompletedSoloDraft=useCallback(()=>{localStorage.removeItem(LS_KEY);LEGACY_DRAFT_KEYS.forEach(k=>localStorage.removeItem(k))},[]);
async function handleCollectiveComplete(finalClaimData){try{const roomCode=finalClaimData.roomId,claimantData=finalClaimData.workers?.[0]||{},payload={claimantData,circumstancesData:finalClaimData.circumstances||{},evidenceData:{selected:finalClaimData.evidence||[],files:finalClaimData.evidenceFiles||{}},selectedLegalOptions:finalClaimData.selectedLegalOptions||[],status:"completed",completedAt:new Date().toISOString()};if(isJoiner){const token=finalClaimData.collectiveParticipantId||localStorage.getItem(joinParticipantKey(roomCode));if(!token)throw new Error("PARTICIPANT_TOKEN_REQUIRED");await saveParticipant(roomCode,token,payload);localStorage.removeItem(joinDraftKey(roomCode,token))}else{await saveOwnerParticipant(roomCode,payload);await updateRoom(roomCode,{employer:finalClaimData.employer||{},commonData:{type:finalClaimData.type,subtype:finalClaimData.subtype,employer:finalClaimData.employer||{},selectedLegalOptions:finalClaimData.selectedLegalOptions||[]}})}setError("");setShowCollectiveProgress(true);return true}catch{setError("Не удалось сохранить данные участника на сервере. Попробуйте ещё раз.");return false}}
async function handleFinalize(){try{const room=await getRoom(claimData.roomId);if(!room)throw new Error("ROOM_NOT_FOUND");const completedMembers=getCompletedParticipants(room);if(completedMembers.length<2){setError("Для совместной претензии нужны минимум 2 заполненных участника.");return}await updateRoom(room.room_id,{collectiveFinalized:true,finalizedAt:new Date().toISOString()});setClaimData(prev=>({...prev,employer:room.employer||prev.employer,collectiveMembers:completedMembers,collectiveFinalized:true,completedParticipantsCount:completedMembers.length,workers:completedMembers.map(memberToWorker)}));setError("");setShowCollectiveProgress(false);setCurrentStep(7)}catch{setError("Не удалось загрузить актуальные данные совместной комнаты.")}}
if(joinLoading)return <div className="dm-gen-loading"><span/></div>;if(showCollectiveProgress&&claimData.mode==="collective")return <div className="dm-generator-page"><div className="dm-generator-wrap"><CollectiveProgress claimData={claimData} isOwner={!isJoiner} onFinalize={isJoiner?undefined:handleFinalize}/></div></div>;
const steps={1:<Step1Category claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep}/>,2:<Step2Mode claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep} prevStep={prevStep}/>,3:<Step3Respondent claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep} prevStep={prevStep} isJoiner={isJoiner}/>,4:<Step4Claimants claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep} prevStep={prevStep}/>,5:<Step5Circumstances claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep} prevStep={prevStep}/>,6:<Step6Evidence claimData={claimData} updateClaimData={updateClaimData} nextStep={nextStep} prevStep={prevStep}/>,7:<Step7Generate claimData={claimData} reset={reset} prevStep={prevStep} onSuccessfulSave={claimData.mode==="individual"?clearCompletedSoloDraft:undefined} onCollectiveComplete={claimData.mode==="collective"&&!claimData.collectiveFinalized?handleCollectiveComplete:undefined}/>};
return <div className="dm-generator-page"><div className="dm-generator-wrap"><div className="dm-generator-title"><span>Досудебка · сервис ДокМаркета</span><strong>{isJoiner?"Заполнение совместной претензии":"Создание претензии"}</strong></div>{error&&<p className="dm-gen-error">{error}</p>}{isJoiner&&<div className="dm-join-note"><span>Участник</span><p><b>Совместная претензия.</b> Заполните только свои личные данные.</p></div>}<StepIndicator currentStep={isJoiner?currentStep-1:currentStep} totalSteps={isJoiner?totalSteps-2:totalSteps}/><div className="dm-generator-step">{steps[currentStep]}</div></div><style>{`
.dm-generator-page{min-height:100vh;padding:22px 12px 90px;background:#07111d;color:#f8fafc}.dm-generator-wrap{width:min(900px,100%);margin:0 auto}.dm-generator-title{display:grid;gap:4px;margin:0 0 14px}.dm-generator-title span{color:#ff9f1c;font-size:.68rem;font-weight:850;text-transform:uppercase;letter-spacing:.08em}.dm-generator-title strong{font-size:1.45rem}.dm-gen-error{padding:10px 12px;border-radius:10px;background:#291d0d;border:1px solid #6a481b;color:#ffc36e;font-size:.78rem}.dm-join-note{display:flex;align-items:center;gap:10px;padding:11px 12px;margin-bottom:14px;border-radius:12px;background:#111d29;border:1px solid #294052}.dm-join-note>span{padding:5px 8px;border-radius:8px;background:#21180d;color:#ffad42;font-size:.66rem;font-weight:850}.dm-join-note p{margin:0;color:#b9c4d0;font-size:.78rem}.dm-generator-step{margin-top:18px}.dm-generator-page .bg-gray-800\/50,.dm-generator-page .bg-gray-800,.dm-generator-page .bg-slate-800{background:#0d1b29!important}.dm-generator-page .border-gray-700,.dm-generator-page .border-slate-700,.dm-generator-page .border-purple-500\/30{border-color:#294052!important}.dm-generator-page .text-purple-400,.dm-generator-page .text-purple-300,.dm-generator-page .text-blue-400{color:#ffad42!important}.dm-generator-page .bg-purple-600,.dm-generator-page .bg-purple-500,.dm-generator-page .bg-blue-600{background:#f28a16!important}.dm-generator-page input:checked{accent-color:#f28a16}.dm-gen-loading{min-height:70vh;display:grid;place-items:center;background:#07111d}.dm-gen-loading span{width:34px;height:34px;border:3px solid #294052;border-top-color:#ff9f1c;border-radius:50%;animation:dmspin .8s linear infinite}@keyframes dmspin{to{transform:rotate(360deg)}}
@media(max-width:600px){.dm-generator-page{padding:14px 10px 82px}.dm-generator-title strong{font-size:1.18rem}.dm-generator-step{margin-top:12px}.dm-generator-page .max-w-4xl,.dm-generator-page .max-w-3xl,.dm-generator-page .max-w-2xl{max-width:100%!important}.dm-generator-page .p-8,.dm-generator-page .p-6{padding:14px!important}.dm-generator-page .gap-6{gap:10px!important}.dm-generator-page .text-2xl{font-size:1.15rem!important}.dm-generator-page button{min-height:44px}}
`}</style></div>}
