import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getPublicSellerProfile } from "@/marketplace/services/sellerProfileService";
import { loadPublishedCatalog } from "@/marketplace/services/catalogService";
import { listSellerReviews } from "@/marketplace/services/reviewService";
import { isFavorite, toggleFavorite } from "@/marketplace/services/favoritesService";
import { MarketFrame, MarketNavigation, OffersGrid } from "./Market";

const TABS=[["store","Витрина"],["reviews","Отзывы"],["about","О селлере"]];
const initialsOf=name=>String(name||"Селлер").split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join("").toUpperCase();
const formatDate=value=>value?new Date(value).toLocaleDateString("ru-RU",{day:"2-digit",month:"long",year:"numeric"}):"";
function Heart({filled=false}){return <svg viewBox="0 0 24 24" width="18" height="18" fill={filled?"currentColor":"none"} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/></svg>}

export default function MarketSpecialist(){
 const{specialistId}=useParams();const[activeTab,setActiveTab]=useState("store");const[,setRevision]=useState(0);const[seller,setSeller]=useState(null);const[items,setItems]=useState([]);const[reviews,setReviews]=useState([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;setLoading(true);Promise.all([getPublicSellerProfile(specialistId),loadPublishedCatalog(),listSellerReviews(specialistId)]).then(([profile,catalog,reviewRows])=>{if(!active)return;setSeller(profile);setItems(profile?(catalog||[]).filter(item=>item.providerId===profile.user_id):[]);setReviews(profile?(reviewRows||[]):[])}).catch(()=>{if(active){setSeller(null);setItems([]);setReviews([])}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[specialistId]);
 if(loading)return <MarketFrame><MarketNavigation crumbs={[{label:"ДокМаркет",to:"/market"},{label:"Селлер"}]} backTo="/market"/><section className="market-empty market-glass"><h1 className="market-heading">Загружаем витрину…</h1></section></MarketFrame>;
 if(!seller)return <MarketFrame><MarketNavigation crumbs={[{label:"ДокМаркет",to:"/market"},{label:"Селлеры"}]} backTo="/market"/><section className="market-empty market-glass"><h1 className="market-heading">Профиль не опубликован</h1><p>В каталоге показываются только реальные селлеры, прошедшие модерацию ДокМаркета.</p><Link className="market-primary" to="/market">Вернуться в каталог</Link></section></MarketFrame>;
 const favorite=isFavorite(seller.user_id,"specialist"),documents=items.filter(item=>item.type!=="service"),services=items.filter(item=>item.type==="service"),allStore=[...documents,...services],rating=Number(seller.rating||0);
 return <MarketFrame>
  <style>{`
  .seller-hero{display:grid;gap:16px}.seller-topline{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.market-profile-head{display:flex;gap:14px;align-items:center}.market-profile-avatar{width:72px;height:72px;border-radius:20px;display:grid;place-items:center;background:linear-gradient(145deg,#182b3d,#244258);border:1px solid #355066;color:#fff;font-size:1.25rem;font-weight:900;flex:0 0 72px}.market-profile-copy h1{margin:5px 0}.seller-verified{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:#132419;border:1px solid #31593c;color:#83e09b;font-size:.62rem;font-weight:850}.seller-fav{width:42px;height:42px;border-radius:50%;border:1px solid #30485a;background:#0b1825;color:#cbd5e1;display:grid;place-items:center;flex:0 0 42px}.seller-fav.active{color:#ff9f1c;border-color:#6a481b;background:#21180d}.market-profile-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.market-profile-stats>div{padding:11px;border-radius:13px;background:#091723;border:1px solid #20384a;display:grid;gap:4px}.market-profile-stats span{color:#76899c;font-size:.61rem}.market-profile-stats strong{color:#fff;font-size:.82rem}.market-offer-actions{display:flex;gap:8px;flex-wrap:wrap}.market-tabs{display:flex;gap:7px;margin:16px 0;overflow:auto;scrollbar-width:none}.market-tabs button{border:1px solid #294052;background:#0e1b28;color:#9babbc;border-radius:999px;padding:8px 12px;font-weight:800;font-size:.72rem}.market-tabs button.active{background:#21180d;border-color:#6a481b;color:#ffb65f}.seller-review-list{display:grid;gap:9px}.seller-review-card{padding:14px;border-radius:15px}.seller-review-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:8px}.seller-review-stars{color:#ffb34d;letter-spacing:1px}.seller-review-card p{margin:0 0 8px;color:#cbd5e1;line-height:1.55;font-size:.78rem}.seller-review-card small{color:#718397;font-size:.64rem}.verified-order{display:inline-flex;align-items:center;gap:5px;color:#83e09b!important}.seller-store-summary{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 14px}.seller-store-summary span{padding:6px 9px;border-radius:999px;background:#0f1d2a;border:1px solid #294052;color:#cbd5e1;font-size:.65rem;font-weight:750}.market-deal-note{margin:12px 0;padding:12px 14px;border-radius:13px;display:grid;gap:3px}.market-deal-note strong{color:#fff;font-size:.78rem}.market-deal-note span{color:#8192a5;font-size:.7rem;line-height:1.45}
  @media(max-width:620px){.seller-topline{gap:8px}.market-profile-avatar{width:56px;height:56px;flex-basis:56px;border-radius:15px;font-size:1rem}.market-profile-copy .market-subtitle{font-size:.74rem}.market-profile-stats{grid-template-columns:repeat(2,1fr)}.market-profile-stats>div{padding:9px}.market-offer-actions .market-action{flex:1;min-width:120px}.seller-review-card{padding:12px}.seller-review-head{align-items:flex-start;flex-direction:column;gap:4px}}
  `}</style>
  <MarketNavigation crumbs={[{label:"ДокМаркет",to:"/market"},{label:"Селлеры"},{label:seller.display_name}]} backTo="/market"/>
  <section className="market-panel market-glass seller-hero"><div className="seller-topline"><div className="market-profile-head"><div className="market-profile-avatar">{initialsOf(seller.display_name)}</div><div className="market-profile-copy"><span className="seller-verified">✓ Проверенный селлер</span><h1 className="market-heading">{seller.display_name}</h1><p className="market-subtitle" style={{margin:0}}>{seller.headline||"Селлер ДокМаркета"}</p></div></div><button className={`seller-fav ${favorite?"active":""}`} type="button" aria-label={favorite?"Убрать селлера из избранного":"Добавить селлера в избранное"} onClick={()=>{toggleFavorite(seller.user_id,"specialist");setRevision(v=>v+1)}}><Heart filled={favorite}/></button></div>
   {(seller.specializations||[]).length>0&&<div className="market-examples">{seller.specializations.map(x=><span className="market-example" key={x}>{x}</span>)}</div>}
   <div className="market-profile-stats"><div><span>Рейтинг</span><strong>{rating>0?`★ ${rating.toFixed(1)}`:"Новый"}</strong></div><div><span>Отзывы</span><strong>{reviews.length||Number(seller.reviews_count||0)}</strong></div><div><span>Заказов</span><strong>{Number(seller.completed_orders||0)}</strong></div><div><span>Услуги</span><strong>{seller.price_from?`от ${Number(seller.price_from).toLocaleString("ru-RU")} ₽`:"По карточкам"}</strong></div></div>
   <div className="market-offer-actions"><button className="market-action primary" onClick={()=>setActiveTab("store")}>Смотреть витрину</button>{reviews.length>0&&<button className="market-action" onClick={()=>setActiveTab("reviews")}>Отзывы · {reviews.length}</button>}</div>
  </section>
  <div className="market-deal-note market-glass"><strong>Заказ проходит внутри ДокМаркета</strong><span>Услуга считается завершённой после передачи результата и подтверждения покупателем. Только после завершённого заказа появляется подтверждённый отзыв.</span></div>
  <nav className="market-tabs">{TABS.map(([id,label])=><button type="button" className={activeTab===id?"active":""} onClick={()=>setActiveTab(id)} key={id}>{label}</button>)}</nav>
  {activeTab==="store"&&<section><h2 className="market-heading" style={{fontSize:"1.4rem"}}>Витрина селлера</h2><p className="market-lead">Документы и услуги этого специалиста.</p><div className="seller-store-summary"><span>{documents.length} документов</span><span>{services.length} услуг</span><span>{reviews.length} отзывов после заказов</span></div>{allStore.length?<OffersGrid items={allStore}/>:<div className="market-empty market-glass">У селлера пока нет опубликованных товаров.</div>}</section>}
  {activeTab==="reviews"&&<section><h2 className="market-heading" style={{fontSize:"1.4rem"}}>Отзывы клиентов</h2><p className="market-lead">Здесь показываются отзывы, связанные с завершёнными заказами.</p>{reviews.length?<div className="seller-review-list">{reviews.map(review=><article className="seller-review-card market-glass" key={review.id}><div className="seller-review-head"><span className="seller-review-stars">{"★".repeat(Number(review.rating||0))}{"☆".repeat(Math.max(0,5-Number(review.rating||0)))}</span><small>{formatDate(review.created_at)}</small></div><p>{review.review_text}</p><small className="verified-order">✓ Подтверждённый заказ · №{String(review.order_id).slice(0,8).toUpperCase()}</small></article>)}</div>:<div className="market-empty market-glass">Пока нет отзывов после завершённых заказов.</div>}</section>}
  {activeTab==="about"&&<section className="market-panel market-glass"><h2 className="market-heading" style={{fontSize:"1.4rem"}}>О селлере</h2><p className="market-copy">{seller.bio||"Селлер пока не добавил подробное описание."}</p><div className="market-choice-grid"><div className="market-choice"><h3>Специализация</h3><p>{(seller.specializations||[]).join(", ")||"Не указана"}</p></div><div className="market-choice"><h3>Модерация</h3><p>Публичный профиль доступен только после проверки ДокМаркетом.</p></div></div></section>}
 </MarketFrame>
}
