import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import { confirmServiceTask, listBuyerServiceTasks } from "@/marketplace/services/serviceTaskService";
import { MarketFrame, MarketNavigation } from "./Market";

const LABELS={new:"Новый",accepted:"Принят",in_progress:"В работе",delivered:"Результат готов",revision:"На доработке",completed:"Завершён",cancelled:"Отменён"};

export default function MyServiceOrders(){
 const {user}=useAuth(); const [tasks,setTasks]=useState([]); const [busy,setBusy]=useState(""); const [error,setError]=useState("");
 const load=()=>user?.id?listBuyerServiceTasks(user.id).then(setTasks).catch(()=>setError("Не удалось загрузить заказы специалистов.")):Promise.resolve();
 useEffect(()=>{load()},[user?.id]);
 async function confirm(task,action){setBusy(task.id);setError("");try{await confirmServiceTask(task.id,action);await load()}catch{setError("Не удалось обновить заказ. Попробуйте ещё раз.")}finally{setBusy("")}}
 return <MarketFrame><style>{css}</style><MarketNavigation crumbs={[{label:"ДокМаркет",to:"/"},{label:"Мои заказы специалистов"}]} backTo="/Dashboard"/>
  <section className="service-orders-head"><div><span className="market-kicker">МОИ ЗАКАЗЫ</span><h1 className="market-heading">Работа со специалистами</h1><p className="market-lead">Здесь видно, принят ли заказ, идёт ли работа и когда специалист передал результат.</p></div><Link className="market-action" to="/market#specialists">Найти специалиста</Link></section>
  {error&&<div className="service-error">{error}</div>}
  {tasks.length?<div className="service-task-list">{tasks.map(task=><article className="service-task market-glass" key={task.id}><div className="service-task-top"><div><span className={`service-status s-${task.status}`}>{LABELS[task.status]||task.status}</span><h2>{task.title}</h2><small>Заказ №{String(task.order_id).slice(0,8).toUpperCase()}</small></div><span className="service-date">{new Date(task.created_at).toLocaleDateString("ru-RU")}</span></div>
   <div className="service-progress"><span className={step(task.status,0)}>Заказ</span><i/><span className={step(task.status,1)}>В работе</span><i/><span className={step(task.status,2)}>Результат</span><i/><span className={step(task.status,3)}>Принят</span></div>
   {task.customer_note&&<div className="service-box"><b>Ваша задача</b><p>{task.customer_note}</p></div>}
   {task.seller_note&&<div className="service-box"><b>Комментарий специалиста</b><p>{task.seller_note}</p></div>}
   {task.result_text&&<div className="service-result"><b>Результат</b><p>{task.result_text}</p>{task.result_url&&<a href={task.result_url} target="_blank" rel="noreferrer">Открыть файл / результат →</a>}</div>}
   {task.status==="delivered"&&<div className="service-confirm"><strong>Проверьте результат</strong><p>Если всё выполнено — подтвердите. Если нужны исправления — отправьте на доработку.</p><div><button disabled={busy===task.id} onClick={()=>confirm(task,"complete")}>Всё выполнено</button><button className="secondary" disabled={busy===task.id} onClick={()=>confirm(task,"revision")}>Нужна доработка</button></div></div>}
   {task.status==="completed"&&<div className="service-done">✓ Работа подтверждена вами и заказ завершён.</div>}
  </article>)}</div>:<div className="market-empty market-glass"><h2>Заказов специалистам пока нет</h2><p>Выберите услугу в карточке продавца. После оформления работа появится здесь.</p><Link className="market-primary" to="/market#specialists">Открыть специалистов</Link></div>}
 </MarketFrame>
}
function step(status,index){const map={new:0,accepted:1,in_progress:1,revision:1,delivered:2,completed:3,cancelled:0};return (map[status]??0)>=index?"active":""}
const css=`.service-orders-head{display:flex;justify-content:space-between;gap:18px;align-items:end;margin-bottom:18px}.service-orders-head .market-lead{margin-bottom:0}.service-task-list{display:grid;gap:14px}.service-task{padding:20px;border-radius:20px}.service-task-top{display:flex;justify-content:space-between;gap:12px}.service-task h2{color:#fff;font-size:1.05rem;margin:8px 0 4px}.service-task small,.service-date{color:#64748b;font-size:.7rem}.service-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(103,232,249,.08);border:1px solid rgba(103,232,249,.16);color:#a5f3fc;font-size:.65rem;font-weight:800}.s-delivered{color:#fde68a;border-color:rgba(251,191,36,.2);background:rgba(251,191,36,.06)}.s-completed{color:#a7f3d0;border-color:rgba(52,211,153,.2);background:rgba(52,211,153,.06)}.service-progress{display:grid;grid-template-columns:auto 1fr auto 1fr auto 1fr auto;align-items:center;gap:7px;margin:18px 0}.service-progress span{font-size:.62rem;color:#64748b}.service-progress span.active{color:#67e8f9;font-weight:800}.service-progress i{height:1px;background:rgba(148,163,184,.16)}.service-box,.service-result,.service-confirm{margin-top:12px;padding:13px;border-radius:13px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.07)}.service-box b,.service-result b,.service-confirm strong{color:#e2e8f0;font-size:.76rem}.service-box p,.service-result p,.service-confirm p{color:#94a3b8;font-size:.78rem;line-height:1.55;margin:6px 0 0}.service-result{border-color:rgba(103,232,249,.15)}.service-result a{display:inline-block;margin-top:9px;color:#67e8f9;font-size:.75rem}.service-confirm div{display:flex;gap:8px;margin-top:11px}.service-confirm button{border:0;padding:10px 13px;border-radius:10px;background:linear-gradient(135deg,#0891b2,#7c3aed);color:#fff;font-weight:800;font-size:.75rem}.service-confirm button.secondary{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1)}.service-done{margin-top:12px;color:#a7f3d0;font-size:.76rem}.service-error{padding:10px 12px;border-radius:10px;background:rgba(244,63,94,.08);color:#fda4af;margin-bottom:12px}@media(max-width:640px){.service-orders-head{align-items:flex-start;flex-direction:column}.service-task{padding:15px}.service-progress span{font-size:.56rem}.service-confirm div{display:grid}.service-confirm button{width:100%}}`;