import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import { AuthShell, Label, ErrorText, fieldStyle, button } from "./Login";
import { ERRORS, isValidRuPhone, normalizePhoneRu, validateEmail, validateFullName, validatePassword, validatePasswordConfirm } from "@/utils/authValidation";

function EyeIcon({off=false}){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>{off&&<path d="M4 4 20 20"/>}</svg>}
const initial={fullName:"",email:"",phone:"",password:"",confirmPassword:"",personalData:false,terms:false};
export default function Register(){
 const{registerUser}=useAuth();const navigate=useNavigate();const[form,setForm]=useState(initial);const[errors,setErrors]=useState({});const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[showPassword,setShowPassword]=useState(false);const[showConfirm,setShowConfirm]=useState(false);
 function setValue(name,value){setForm(c=>({...c,[name]:value}));setErrors(c=>({...c,[name]:"",form:""}));setNotice("")}
 function validate(){const next={fullName:validateFullName(form.fullName),email:validateEmail(form.email),phone:isValidRuPhone(form.phone)?"":ERRORS.phone,password:validatePassword(form.password),confirmPassword:validatePasswordConfirm(form.password,form.confirmPassword),personalData:form.personalData?"":ERRORS.consent,terms:form.terms?"":ERRORS.consent};setErrors(next);return!Object.values(next).some(Boolean)}
 async function submit(e){e.preventDefault();if(!validate())return;setBusy(true);setNotice("");try{await registerUser({...form,email:form.email.trim().toLowerCase()});navigate("/Dashboard",{replace:true})}catch(error){if(error.message==="EMAIL_CONFIRMATION_REQUIRED")setNotice("Аккаунт создан. Подтвердите email по письму, затем войдите.");else setErrors(c=>({...c,form:error.message==="EMAIL_EXISTS"?"Аккаунт с таким email уже существует.":"Не удалось создать аккаунт. Проверьте данные."}))}finally{setBusy(false)}}
 return <AuthShell title="Создать аккаунт" subtitle="Покупайте документы, храните покупки, заказывайте услуги селлеров и пользуйтесь сервисами ДокМаркета.">
  <form onSubmit={submit} noValidate style={{display:"grid",gap:10}}>
   <Field name="fullName" label="ФИО" placeholder="Иванов Иван Иванович" value={form.fullName} error={errors.fullName} onChange={setValue}/>
   <Field name="email" label="Email" type="email" placeholder="name@example.ru" value={form.email} error={errors.email} onChange={setValue}/>
   <Field name="phone" label="Телефон" type="tel" inputMode="tel" placeholder="+7 (999) 999-99-99" value={form.phone} error={errors.phone} onChange={(n,v)=>setValue(n,normalizePhoneRu(v))}/>
   <PasswordField name="password" label="Пароль" placeholder="Минимум 8 символов" value={form.password} error={errors.password} onChange={setValue} visible={showPassword} onToggle={()=>setShowPassword(v=>!v)} hint="Минимум 8 символов, буквы и цифры."/>
   <PasswordField name="confirmPassword" label="Повторите пароль" placeholder="Повторите пароль" value={form.confirmPassword} error={errors.confirmPassword} onChange={setValue} visible={showConfirm} onToggle={()=>setShowConfirm(v=>!v)}/>
   <div className="dm-auth-consents"><Consent checked={form.personalData} onChange={v=>setValue("personalData",v)} error={errors.personalData}>Я согласен на <Link to="/privacy" target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>обработку персональных данных</Link></Consent><Consent checked={form.terms} onChange={v=>setValue("terms",v)} error={errors.terms}>Я принимаю <Link to="/terms" target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>пользовательское соглашение ДокМаркета</Link></Consent></div>
   {notice&&<p role="status" style={{color:"#86efac",margin:0,fontSize:".76rem",lineHeight:1.4}}>{notice}</p>}{errors.form&&<ErrorText>{errors.form}</ErrorText>}
   <button style={{...button,minHeight:46,marginTop:2,opacity:busy?.7:1}} disabled={busy}>{busy?"Создаём…":"Создать аккаунт"}</button>
  </form>
  <div style={{display:"grid",gap:7,marginTop:14}}><Link to="/Login" style={{color:"#ffb65f",fontSize:".82rem",fontWeight:750}}>Уже есть аккаунт? Войти</Link><Link to="/RegisterLawyer" style={{color:"#91a1b3",fontSize:".76rem"}}>Хотите продавать документы или услуги? Стать селлером</Link></div>
 </AuthShell>;
}
export function Field({name,label,type="text",placeholder,value,error,onChange,hint,inputMode}){return <Label text={label}><input style={{...fieldStyle(error),padding:"11px 13px"}} type={type} inputMode={inputMode} placeholder={placeholder} value={value} onChange={e=>onChange(name,e.target.value)} aria-invalid={Boolean(error)}/>{hint&&!error&&<span style={hintStyle}>{hint}</span>}{error&&<ErrorText>{error}</ErrorText>}</Label>}
function PasswordField({name,label,placeholder,value,error,onChange,visible,onToggle,hint}){return <Label text={label}><div style={{position:"relative"}}><input style={{...fieldStyle(error),padding:"11px 46px 11px 13px"}} type={visible?"text":"password"} placeholder={placeholder} value={value} onChange={e=>onChange(name,e.target.value)} aria-invalid={Boolean(error)}/><button type="button" aria-label={visible?"Скрыть пароль":"Показать пароль"} onClick={onToggle} style={eyeButton}><EyeIcon off={visible}/></button></div>{hint&&!error&&<span style={hintStyle}>{hint}</span>}{error&&<ErrorText>{error}</ErrorText>}</Label>}
export function Consent({checked,onChange,error,children}){return <div><label style={consentStyle}><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} style={{width:18,height:18,accentColor:"#ff9f1c",flex:"0 0 auto",marginTop:1}}/><span>{children}</span></label>{error&&<ErrorText>{error}</ErrorText>}</div>}
const hintStyle={color:"#617386",fontSize:".69rem",lineHeight:1.3};const consentStyle={display:"flex",alignItems:"flex-start",gap:8,color:"#cbd5e1",fontSize:".74rem",lineHeight:1.4,cursor:"pointer"};const eyeButton={position:"absolute",right:5,top:"50%",transform:"translateY(-50%)",width:36,height:36,border:0,borderRadius:9,background:"transparent",color:"#91a1b3",cursor:"pointer",display:"grid",placeItems:"center"};
