import { Link } from "react-router-dom";
import { useAuth } from "@/lib/AuthContext";
import { MarketFrame, MarketNavigation } from "./Market";

const cards=[
 {to:"/specialist/orders",icon:"fa-bag-shopping",title:"Заказы",text:"Новые задачи, работа, передача результата и подтверждение клиента."},
 {to:"/specialist/materials",icon:"fa-box-open",title:"Мои товары",text:"Документы, шаблоны и материалы, которые продаются в ДокМаркете."},
 {to:"/specialist/materials/new",icon:"fa-circle-plus",title:"Добавить товар",text:"Создайте карточку документа или материала для модерации."},
 {to:"/template-studio",icon:"fa-file-pen",title:"Конструктор",text:"Собирайте шаблоны и автоматические документы внутри платформы."},
];

export default function SellerCabinet(){
 const {user}=useAuth(); const name=user?.fullName||user?.full_name||user?.name||"Продавец";
 return <MarketFrame><style>{css}</style><MarketNavigation crumbs={[{label:"ДокМаркет",to:"/"},{label:"Кабинет продавца"}]} backTo="/"/>
  <section className="seller-cab-hero market-glass"><div><span className="market-kicker">ДОКМАРКЕТ · ПРОДАВЕЦ</span><h1 className="market-heading">{name}</h1><p className="market-lead">Управляйте товарами и заказами в одном месте. Покупатель видит вашу витрину, оформляет заказ и получает результат внутри ДокМаркета.</p></div><Link className="market-primary" to="/specialist/materials/new">+ Добавить товар</Link></section>
  <section className="seller-cab-flow market-glass"><strong>Как проходит продажа услуги</strong><div><span>1. Заказ</span><i>→</i><span>2. Принять</span><i>→</i><span>3. Выполнить</span><i>→</i><span>4. Передать</span><i>→</i><span>5. Клиент подтверждает</span></div><p>Платёжная часть подключается отдельно. Интерфейс уже готов к схеме, где расчёт с исполнителем происходит после подтверждения результата.</p></section>
  <section><div className="seller-cab-title"><div><span className="market-kicker">РАБОЧЕЕ МЕСТО</span><h2 className="market-heading">Что хотите сделать?</h2></div></div><div className="seller-cab-grid">{cards.map(card=><Link className="seller-cab-card market-glass" to={card.to} key={card.title}><span><i className={`fa-solid ${card.icon}`}/></span><div><h3>{card.title}</h3><p>{card.text}</p></div><i className="fa-solid fa-arrow-right"/></Link>)}</div></section>
  <section className="seller-cab-notice market-glass"><div><span className="market-kicker">ВИТРИНА</span><h2>Продавец — это специалист внутри маркетплейса</h2><p>Ваши документы и услуги находятся рядом. Покупатель может сначала купить готовый файл, а затем заказать у вас помощь по той же теме.</p></div><Link className="market-action" to="/market">Посмотреть каталог</Link></section>
 </MarketFrame>
}
const css=`.seller-cab-hero{border-radius:22px;padding:22px;display:flex;align-items:end;justify-content:space-between;gap:20px;margin-bottom:14px}.seller-cab-hero .market-lead{max-width:760px;margin-bottom:0}.seller-cab-flow{padding:17px;border-radius:17px;margin-bottom:26px}.seller-cab-flow>strong{color:#fff}.seller-cab-flow>div{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:11px 0}.seller-cab-flow span{padding:7px 9px;border-radius:9px;background:rgba(103,232,249,.06);border:1px solid rgba(103,232,249,.12);color:#cbd5e1;font-size:.7rem;font-weight:750}.seller-cab-flow i{color:#475569}.seller-cab-flow p{margin:0;color:#64748b;font-size:.73rem;line-height:1.5}.seller-cab-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.seller-cab-card{padding:17px;border-radius:17px;text-decoration:none;color:inherit;display:grid;grid-template-columns:auto 1fr auto;gap:13px;align-items:center}.seller-cab-card>span{width:43px;height:43px;display:grid;place-items:center;border-radius:12px;background:rgba(34,211,238,.08);color:#67e8f9}.seller-cab-card h3{color:#fff;margin:0 0 5px;font-size:.93rem}.seller-cab-card p{color:#94a3b8;margin:0;font-size:.74rem;line-height:1.45}.seller-cab-card>i{color:#475569}.seller-cab-notice{margin-top:26px;padding:20px;border-radius:18px;display:flex;align-items:center;justify-content:space-between;gap:18px}.seller-cab-notice h2{color:#fff;margin:3px 0 6px;font-size:1rem}.seller-cab-notice p{color:#94a3b8;margin:0;font-size:.78rem;line-height:1.5;max-width:720px}@media(max-width:640px){.seller-cab-hero{align-items:stretch;display:grid;padding:17px}.seller-cab-hero .market-primary{width:100%}.seller-cab-grid{grid-template-columns:1fr}.seller-cab-card{padding:14px}.seller-cab-flow>div{display:grid;grid-template-columns:1fr}.seller-cab-flow i{display:none}.seller-cab-notice{align-items:stretch;display:grid}.seller-cab-notice .market-action{width:100%}}`;