import { useEffect, useState } from "react";
import { useAuth } from "@/lib/AuthContext";
import { listSellerServiceTasks, updateSellerServiceTask } from "@/marketplace/services/serviceTaskService";
import { MarketFrame, MarketNavigation } from "./Market";

const LABELS={new:"Новый",accepted:"Принят",in_progress:"В работе",delivered:"Передан клиенту",revision:"Нужна доработка",completed:"Завершён",cancelled:"Отменён"};

export default function SpecialistOrders(){
 const {user}=useAuth(); const [tasks,setTasks]=useState([]); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [drafts,setDrafts]=useState({});
 const load=()=>user?.id?listSellerServiceTasks(user.id).then(setTasks).catch(()=>setError("Не удалось загрузить заказы.")):Promise.resolve();
 useEffect(()=>{load()},[user?.id]);
 const draft=(id,key,fallback="")=>drafts[id]?.[key]??fallback; const setDraft=(id,key,value)=>setDrafts(s=>({...s,[id]:{...(s[id]||{}),[key]:value}}));
 async function update(task,patch){setBusy(task.id);setError("");try{await updateSellerServiceTask(task.id,patch);await load()}catch{setError("Не удалось обновить заказ.")}finally{setBusy("")}}
 return <MarketFrame><style>{css}</style><MarketNavigation crumbs={[{label:"ДокМаркет",to:"/"},{label:"Кабинет селлера",to:"/BusinessCabinet"},{label:"Заказы"}]} backTo="/BusinessCabinet"/>
  <section className="seller-orders-head"><div><span className="market-kicker">КАБИНЕТ СЕЛЛЕРА</span><h1 className="market-heading">Заказы на услуги</h1><p className="market-lead">Вся работа идёт внутри заказа: приняли задачу, выполнили, передали результат, клиент подтвердил.</p></div></section>
  {error&&<div className="seller-error">{error}</div>}
  {tasks.length?<div className="seller-task-list">{tasks.map(task=><article className="seller-task market-glass" key={task.id}><div className="seller-task-top"><div><span className={`seller-status s-${task.status}`}>{LABELS[task.status]||task.status}</span><h2>{task.title}</h2><small>Заказ №{String(task.order_id).slice(0,8).toUpperCase()}</small></div><span>{new Date(task.created_at).toLocaleDateString("ru-RU")}</span></div>
    {task.customer_note&&<div className="seller-box"><b>Задача клиента</b><p>{task.customer_note}</p></div>}
    {task.status==="new"&&<div className="seller-actions"><button disabled={busy===task.id} onClick={()=>update(task,{status:"accepted"})}>Принять заказ</button><button className="secondary" disabled={busy===task.id} onClick={()=>update(task,{status:"cancelled"})}>Отказаться</button></div>}
    {task.status==="accepted"&&<div className="seller-actions"><button disabled={busy===task.id} onClick={()=>update(task,{status:"in_progress"})}>Начать работу</button></div>}
    {["in_progress","revision"].includes(task.status)&&<div className="seller-work"><label>Комментарий клиенту<textarea value={draft(task.id,"seller_note",task.seller_note||"")} onChange={e=>setDraft(task.id,"seller_note",e.target.value)} placeholder="Что сделано, что нужно уточнить"/></label><label>Результат<textarea value={draft(task.id,"result_text",task.result_text||"")} onChange={e=>setDraft(task.id,"result_text",e.target.value)} placeholder="Опишите результат работы"/></label><label>Ссылка на файл или результат<input value={draft(task.id,"result_url",task.result_url||"")} onChange={e=>setDraft(task.id,"result_url",e.target.value)} placeholder="https://..."/></label><button disabled={busy===task.id||!draft(task.id,"result_text",task.result_text||"").trim()} onClick={()=>update(task,{status:"delivered",seller_note:draft(task.id,"seller_note",task.seller_note||""),result_text:draft(task.id,"result_text",task.result_text||""),result_url:draft(task.id,"result_url",task.result_url||"")})}>Передать результат клиенту</button></div>}
    {task.status==="delivered"&&<div className="seller-wait"><b>Результат передан</b><p>Теперь клиент проверяет работу. Он сможет подтвердить результат или отправить его на доработку.</p></div>}
    {task.status==="completed"&&<div className="seller-done">✓ Клиент подтвердил результат. Заказ завершён.</div>}
  </article>)}</div>:<div className="market-empty market-glass"><h2>Новых заказов пока нет</h2><p>Когда покупатель оформит вашу услугу, заказ появится здесь.</p></div>}
 </MarketFrame>
}
const css=`.seller-orders-head{margin-bottom:18px}.seller-orders-head .market-lead{margin-bottom:0}.seller-task-list{display:grid;gap:14px}.seller-task{padding:20px;border-radius:20px}.seller-task-top{display:flex;justify-content:space-between;gap:12px}.seller-task-top>span,.seller-task small{color:#64748b;font-size:.7rem}.seller-task h2{color:#fff;font-size:1.05rem;margin:8px 0 4px}.seller-status{display:inline-flex;padding:5px 8px;border-radius:999px;background:rgba(103,232,249,.08);border:1px solid rgba(103,232,249,.16);color:#a5f3fc;font-size:.65rem;font-weight:800}.s-revision{color:#fde68a}.s-completed{color:#a7f3d0}.seller-box,.seller-work,.seller-wait{margin-top:13px;padding:13px;border-radius:13px;background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.07)}.seller-box b,.seller-wait b{color:#e2e8f0;font-size:.77rem}.seller-box p,.seller-wait p{color:#94a3b8;font-size:.78rem;line-height:1.55;margin:6px 0 0}.seller-actions{display:flex;gap:8px;margin-top:13px}.seller-actions button,.seller-work button{border:0;padding:10px 13px;border-radius:10px;background:linear-gradient(135deg,#0891b2,#7c3aed);color:#fff;font-size:.75rem;font-weight:800}.seller-actions .secondary{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.1)}.seller-work{display:grid;gap:10px}.seller-work label{display:grid;gap:5px;color:#cbd5e1;font-size:.72rem}.seller-work textarea,.seller-work input{width:100%;border-radius:10px;border:1px solid rgba(148,163,184,.15);background:rgba(2,6,23,.45);color:#fff;padding:10px;outline:none}.seller-work textarea{min-height:85px;resize:vertical}.seller-work button{justify-self:start}.seller-done{margin-top:13px;color:#a7f3d0;font-size:.78rem}.seller-error{padding:10px 12px;border-radius:10px;background:rgba(244,63,94,.08);color:#fda4af;margin-bottom:12px}@media(max-width:640px){.seller-task{padding:15px}.seller-actions{display:grid}.seller-actions button,.seller-work button{width:100%}.seller-work button{justify-self:stretch}}`;
